defaults: &defaults # default use json-db,express,javascript
  project:
    name: project-name
    version: 0.0.1
    description: Project Name
    port: 3000
    module: users
    basePath: '/api/v1'
    templateSwitch: nodejs
  projectStyle:
    language:
      name: JavaScript
      isJavaScript: false
      isTypeScript: false
      isJava: false
    server:
      name: Express
      isExpress: true
      isKoa: false
    db:
      name: challenge
      isJsonDB: false
      isMongoDB: false
      isNeo4j: false
      isMysql: false
      isDynamoDB: false
    deploy:
      useDocker: true
      useHeroku: false
    maven:
      groupId: ''
  apiStyle:
    log:
      needLog: false
      needTest: false
      needCoverage: false
    other:
      needHealthCheck: false
      needOpt: false
      needJwt: false
      needPasswordBcrypt: false
      needTwilio: false
      needAws: false
      needGootleText2Speech: false
    lint:
      isAribnbBase: false
      isESlingStandard: false
      isESlintRecommended: false
    doc:
      isSwaggerDoc: false
    date:
      isThreeTenbp: false
      isJava8: false
      isJoda: false
  devDependencies:
    codeStyle:
      tslint: false
      eslint: false
      eslint-config-airbnb-base: false
      eslint-chai-friendly: false
      babel-eslint: false
      eslint-config-standard: false
      eslint-plugin-node: false
      eslint-plugin-import: false
      eslint-plugin-promise: false
      eslint-plugin-standard: false
    test:
      chai: false
      mocha: false
      sinon: false
      supertest: false
      sinon-mongoose: false
      jest: false
    coverage:
      nyc: false # Istanbul's state of the art command line interface
    other:
      nodemon: true # if false, becareful devDependencies has a extend comma
  dependencies:
    config:
      dotenv: true # load .env
    logger:
      morgan: false # logger
      bunyan: false
    validate:
      joi: true
      validator: false
    secure:
      bcrypt-nodejs: false
      crypto: false
    db:
      json-file-db: false
      mongoose: false
      neo4j-driver: false
    express:
      express-status-monitor: false # monitor express status
      compression: true # compress http response & request
      body-parser: true
      express-validator: true
      cors: true # enable CORS with various options.
      helmet: true # secure Express/Connect apps with various HTTP headers
      lusca: true # Web application security middleware.
      express-jwt: false
      multer: true # Middleware for handling `multipart/form-data
    other:
      http-status: true
      error-handle: true
      uuid: true
      swagger-jsdoc: false
      debug: true
    spring:
      spring-fox: false
      otp-aerogera: false
test:
  apiStyle:
    log:
      needTest: true
  devDependencies:
    test:
      chai: true
      mocha: true
      sinon: true
      supertest: true
      sinon-mongoose: false
      jest: true
cov:
  apiStyle:
    log:
      needCoverage: false
  devDependencies:
    coverage:
      nyc: true
eslint:
  apiStyle:
    lint:
      isESlingStandard: true
  devDependencies:
    codeStyle:
      eslint: true
      babel-eslint: true
      eslint-config-standard: true
      eslint-plugin-import: true
      eslint-plugin-node: true
      eslint-plugin-promise: true
      eslint-plugin-standard: true
tslint:
  devDependencies:
    codeStyle:
      tslint: true
      tslint-config-prettier: true
      tslint-immutable: true
heroku:
  projectStyle:
    deploy:
      useDocker: false
      useHeroku: true
swgdoc:
  apiStyle:
    doc:
      isSwaggerDoc: true
  dependencies:
    other:
      swagger-jsdoc: true
log:
  apiStyle:
    log:
      needLog: true
  dependencies:
    logger:
      morgan: true
koa:
  projectStyle:
    server:
      name: koa
      isExpress: false
      isKoa: true
jwt:
  apiStyle:
    other:
      needJwt: true
  dependencies:
    express:
      express-jwt: true
secure:
  apiStyle:
    needPasswordBcrypt: true
  dependencies:
    secure:
      bcrypt-nodejs: true
      crypto: true
aws:
  apiStyle:
    other:
      needAws: true
  dependencies:
    other:
      aws-sdk: true
twilio:
  apiStyle:
    other:
      needTwilio: true
  dependencies:
    other:
      twilio: true
#### DB
jsondb:
  projectStyle:
    db:
      name: JSON-DB
      isJsonDB: true
  devDependencies:
    test:
      sinon-mongoose: false
  dependencies:
    db:
      json-file-db: true
neo4j:
  projectStyle:
    db:
      name: Neo4j
      isNeo4j: true
  dependencies:
    db:
      neo4j-driver: true
mongo:
  projectStyle:
    db:
      name: MongoDB
      isMongoDB: true
  dependencies:
    db:
      mongoose: true
dynamo:
  projectStyle:
    db:
      name: DynamoDB
      isDynamoDB: true
mysql:
  projectStyle:
    db:
      name: Mysql
      isMysql: true
## Language
typescript:
  projectStyle:
    language:
      name: TypeScript
      isTypeScript: true
javascript:
  projectStyle:
    language:
      name: JavaScript
      isJavaScript: true
spring:
  project:
    templateSwitch: spring
  projectStyle:
    language:
      name: Java
      isJava: true
    maven:
      groupId: com.autocognita
  apiStyle:
    log:
      needLog: true
    other:
      needJwt: true
      needPasswordBcrypt: true
