defaults: &defaults
  project:
    name: autocognita
    basePath: /api/v5/
    templateSwitch: swagger
  api:
    security:
      isJwt: true
    navigation:
      page: page
      perPage: perPage
      sortOrder: sortOrder
  paths:
    - path: /me/usages
      ops:
      - method: get
        operationId:
        operationName:
        tag:
        noSecurity: false
        needAuth: true
        needFound: true
        needPermission: false
        queryParams:
          - name: id
        needReqBody: false
        needReqBodyRef: false
        needResponseRef: false
        responseParams:
          - name: id
        refResponseEntity: nouse remove
        needResponsePageHeader: false
        noResponseContent: false
  schemas:
    - entity: GroupMembership
      entityParams:
        - name: id
